get-ns:
	@kubectl get namespace -A

create-ns-cmd:
	@kubectl create namespace my-namespace

create-ns-file:
	@kubectl apply -f manifest.yaml

clear-ns:
	@kubectl delete -f manifest.yaml
	@kubectl delete namespace my-namespace





