apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemon-set
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
    
  # pod
  template:
    metadata:
      labels:
        app: my-app

    spec:
      containers:
      - name: fluentd-elasticsearch
        image: quay.io/fluentd_elasticsearch/fluentd:v5.0.1
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log

      # it may be desirable to set a high priority class to ensure that a DaemonSet Pod
      # preempts running Pods
      # priorityClassName: important
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log

