apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cron-job
  labels:
    app: my-app
spec:
  schedule: "* * * * *"
  # job 
  jobTemplate:
    metadata:
      labels:
        app: my-app
    spec:
      # pod 
      template:
        metadata:
          labels:
            app: my-app
        spec:
          containers:
          - name: echo
            image: busybox:1.36.1
            command: ["date"]
          restartPolicy: OnFailure
