apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: my-deploy

spec:
  # replica setup
  replicas: 3
  selector:
    matchLabels:
      app: my-pod

  # pod setup
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.0
