apiVersion: v1
kind: Service
metadata:
  name: my-service-lb
  labels:
    app: my-pod
spec:
  type: LoadBalancer
  selector:
    app: my-pod   
  ports:
    - protocol: TCP
      port: 80 # Port the service is listening on
      targetPort: 80 # Port the container is listening on (if unset, defaults to equal port value)